# Generated by Django 5.1.4 on 2024-12-22 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('column', models.IntegerField()),
                ('value', models.IntegerField()),
                ('state', models.CharField(blank=True, choices=[('revealed', 'Revealed'), ('flagged', 'Flagged')], db_index=True, max_length=50, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boardtiles', to='game.game')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('game', 'row', 'column'), name='unique_game_row_column')],
            },
        ),
    ]
