# Generated by Django 5.1.4 on 2024-12-22 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=50)),
                ('status', models.CharField(choices=[('playing', 'Playing'), ('won', 'Won'), ('lost', 'Lost')], default='playing', max_length=50)),
            ],
        ),
    ]
